### ISSUE TITLE
getAccount error

### ISSUE THREAD

**Issue by nfttrader00** [tokenbound/sdk#3]
hi, 

I am trying to understand this SDK how start... I install via npm the current version

and I used this code snippet from your examples: 

`
```
  await getAccount(
        "0xe7134a029cd2fd55f678d6809e64d0b6a0caddcb", // ERC-721 token contract
        "9", // ERC-721 tokenId
        new ethers.InfuraProvider("goerli", INFURA_API_KEY) // ethers provider
      ).catch(err => {
        console.log(err)
      })

```
`

but the codes trows an error when I run its . The error like this : 

`
```
TypeError: no matching function (argument="key", value="callStatic", code=INVALID_ARGUMENT, version=6.4.0)
    at makeError (/.../tba-contracts/node_modules/ethers/lib.commonjs/utils/errors.js:114:21)
    at assert (/.../tba-contracts/node_modules/ethers/lib.commonjs/utils/errors.js:138:15)
    at assertArgument (/.../tba-contracts/node_modules/ethers/lib.commonjs/utils/errors.js:150:5)
    at Interface.getFunctionName (/.../tba-contracts/node_modules/ethers/lib.commonjs/abi/interface.js:337:39)
    at buildWrappedMethod (/.../tba-contracts/node_modules/ethers/lib.commonjs/contract/contract.js:240:34)
    at Contract.getFunction (/.../tba-contracts/node_modules/ethers/lib.commonjs/contract/contract.js:632:22)
    at Object.get (/.../tba-contracts/node_modules/ethers/lib.commonjs/contract/contract.js:567:39)
    at o (/.../tba-contracts/node_modules/@tokenbound/sdk-ethers/dist/tokenbound-sdk.umd.cjs:1:2935)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getContractDetail (/.../tba-contracts/index.js:35:3) {
  code: 'INVALID_ARGUMENT',
  argument: 'key',
  value: 'callStatic'
}
```

`

how can I solve this error? please can u help me??

thank you

**Comment by jaydenwindle** [comment]
Hey @nfttrader00 - which version of ethers are you using? This library only works with v5 at the moment.

**Comment by nfttrader00** [comment]
hmm, I'm using last ethers version @jaydenwindle . I will check it with v5,

thank u

**Comment by nfttrader00** [comment]
hey @jaydenwindle , yes it'll with v.5.x

I'll continue to explore. :)

thank u
